NataliaBraganca/lebkuchen

app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_findus.scss
app/assets/stylesheets/pages/_index.scss
app/views/layouts/application.html.erb
app/views/pages/findus.html.erb

Fonts added and navbar readjusted

Style guide

---

app/assets/stylesheets/components/_map.scss
app/assets/stylesheets/pages/_event.scss
app/javascript/controllers/modal_controller.js
app/views/contacts/new.html.erb

fixed map show, fixed modal, fixed contact us page

fixed map show, fixed modal, fixed contact us page

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/findus.html.erb
app/views/pages/home.html.erb

At homepage, added justify-content-center, in row gy-2 div to align products at center of page.
In Css files, starting the identetion cleanup, to avoid white spaces and wrong spaces in the class or ids.

justify itens center homepage, fix css identetion

---

app/assets/stylesheets/pages/_findus.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/findus.html.erb

add same font to findus as homepage

add same font to findus as homepage

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
yarn.lock

bootstrap added

---

app/assets/stylesheets/application.scss

added bootstrap

---

app/assets/stylesheets/components/_to_top_button.scss
app/assets/stylesheets/pages/_findus.scss
app/javascript/controllers/index.js
app/javascript/controllers/scroll_reveal_controller.js
app/views/layouts/application.html.erb
app/views/shared/_back_to_top.html.erb

added stimulus scroll button reveal

added stimulus scroll button reveal

---

app/views/pages/home.html.erb

fix buttons

---

app/assets/stylesheets/components/_card-title.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_event.scss
app/assets/stylesheets/pages/_findus.scss
app/assets/stylesheets/pages/_home.scss
app/views/contacts/new.html.erb
app/views/pages/product.html.erb

start responsive

---

app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

nacbar color

---

app/assets/stylesheets/pages/_findus.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

added responsivity to photos history at home
need to remake scss styles

added responsivity to photos history at home

---

app/assets/stylesheets/components/_card_event.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Added a radio button with some style to change language
Added popper script to the end of body in case we will use poppers or drop down menus

added changes to front

---

app/assets/stylesheets/pages/_home.scss
app/views/layouts/application.html.erb

Added responsiviness to home banner,h1, h2 and button to smartphones, tablets and computers.

responsive banner and button to all devices

---

app/views/pages/home.html.erb

added responsivity to ipad and tablets

added responsivity to ipad and tablets

---

app/assets/stylesheets/pages/_findus.scss
app/controllers/contacts_controller.rb
app/views/pages/findus.html.erb
app/views/pages/home.html.erb

responsive findus page

---

app/views/pages/findus.html.erb

icon from Font Awesome added ( change the icons from the cards location)

icon from Font Awesome added

---

app/assets/stylesheets/pages/_findus.scss
app/views/pages/findus.html.erb

style icon

---

app/assets/stylesheets/pages/_findus.scss
app/javascript/controllers/application.js
app/views/pages/findus.html.erb

removed banner from media queries iphone and ipad

removed banner from media queries iphone and ipad

---

app/views/pages/findus.html.erb

fix identation

---

app/assets/stylesheets/components/_navbar.scss
app/views/pages/findus.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

responsivity with Andre

---

app/assets/stylesheets/pages/_findus.scss
app/views/pages/findus.html.erb

map responsivity

---

app/controllers/contacts_controller.rb
app/models/contact.rb
app/views/layouts/application.html.erb
app/views/shared/_flash.html.erb
config/routes.rb

fix flash messages in contact mailer

fix flash messages in contact mailer

---

app/assets/stylesheets/pages/_findus.scss

added column reverse to cards

---

app/assets/stylesheets/components/_alert.scss
app/controllers/contacts_controller.rb
app/views/shared/_flash.html.erb

alert fixed

---

app/controllers/contacts_controller.rb
config/routes.rb

routes fixed

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_findus.scss
app/assets/stylesheets/pages/_home.scss
app/views/contacts/new.html.erb
app/views/pages/event.html.erb
app/views/pages/home.html.erb
app/views/pages/product.html.erb
app/views/shared/_navbar.html.erb

products cards on home page changed and some overall style changes

cards and some style changes

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_to_top_button.scss
app/javascript/controllers/scroll_reveal_controller.js

navbar dropdown changed. different hover style

navbar dropdown changed

---

app/assets/stylesheets/components/_to_top_button.scss
app/javascript/controllers/scroll_reveal_controller.js

changed scroll reveal and added box shadow to button

changed scroll reveal and added box shadow to button

---

app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/index.js
app/javascript/controllers/navbar_controller.js
app/views/shared/_navbar.html.erb

added X animation to mobile navigation menu

added X to mobile navigation menu

---

app/assets/stylesheets/components/_navbar.scss
app/javascript/controllers/navbar_controller.js
app/views/shared/_navbar.html.erb

added Hamburger to X, menu shrink action with stimulus js

added Hamburger to X, menu shrink action with stimulus js

---

app/assets/stylesheets/pages/_event.scss
app/assets/stylesheets/pages/_findus.scss

banner fixed - page findus

---

app/assets/stylesheets/pages/_contacts.scss
app/assets/stylesheets/pages/_event.scss
app/views/contacts/new.html.erb

form edited

---

app/views/pages/findus.html.erb
app/views/pages/home.html.erb
config/locales/de.yml
config/locales/en.yml

home page translation completed

home page translation completed

---

config/routes.rb

moved errors routes to routes locate scope

moved errors routes to routes locate scope

---

app/views/contacts/new.html.erb
app/views/pages/home.html.erb
config/locales/de.yml
config/locales/en.yml

fix locale
fix identetion in en and de ynl in locale at config to ident as:
de:
the name

fix locale

---

app/views/pages/cookies_eu.html.erb
app/views/pages/cookies_eu_en.html.erb

added privacy policy deustch and english

added privacy policy deustch and english

---

app/assets/stylesheets/pages/_findus.scss
app/views/pages/findus.html.erb

style page find us

---

app/views/cookies_eu/_consent_banner.html.erb
app/views/pages/cookies_eu.html.erb
config/locales/de.yml
config/locales/en.yml

added language change in cookie banner

added language change in cookie banner

---

app/assets/stylesheets/pages/_product.scss
app/views/pages/product.html.erb

add button to product page

---

app/assets/stylesheets/pages/_home.scss
app/views/errors/internal_server_error.html.erb
app/views/legal/_legal.html.erb
app/views/pages/home.html.erb

Change things and add pages

---

app/assets/stylesheets/pages/_product.scss
app/views/pages/product.html.erb

button (available flavors)  and a bit style product page

button and a bit style product page

---

app/assets/stylesheets/pages/_home.scss
app/controllers/contacts_controller.rb
app/views/pages/cookies_eu.html.erb
config/locales/de.yml
config/locales/en.yml

cookies page translation in progress

translation cookies page in progress

---

app/views/layouts/application.html.erb
package.json
webpack.config.js
yarn.lock

setup carousel

---

app/views/layouts/application.html.erb
app/views/pages/findus.html.erb
app/views/pages/product.html.erb
config/locales/de.yml
config/locales/en.yml

fixed traduction of findus and identetion

fixed traduction of findus and identetion

---

app/controllers/pages_controller.rb

added logic to enhance navigation to i18n

added logic to enhance navigation to i18n

---

app/views/pages/legal.de.html.erb
app/views/pages/legal.en.html.erb
config/routes.rb

continue implementation of legal pages i18n

continue implementation of legal pages i18n

---

app/assets/stylesheets/pages/_product.scss
app/views/pages/product.html.erb

fit slides to div

---

app/controllers/products_controller.rb
app/javascript/controllers/index.js
app/javascript/controllers/slider_controller.js
app/views/layouts/application.html.erb
app/views/pages/product.html.erb
package.json
yarn.lock

added button to slide in product page

added button to slide in product page

---

app/models/contact.rb

set up new email in contact form

email lebkuchenausrodgau added

---

app/assets/stylesheets/pages/_product.scss
app/views/pages/product.html.erb
config/locales/de.yml
config/locales/en.yml

translation de

---

app/views/pages/product.html.erb
config/locales/de.yml
config/locales/en.yml

translation

---

app/javascript/controllers/index.js
app/javascript/controllers/map_controller.js
package.json
yarn.lock

try to fix map in prod

---

app/assets/stylesheets/pages/_product.scss
app/javascript/controllers/slider_controller.js
app/views/pages/product.html.erb

flavor button and swiper button fixed

 flavor button and swiper button fixed 

---

config/locales/de.yml
config/locales/en.yml

errors page

---

app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb

fixed i18n routes
